CREATE TABLE IF NOT EXISTS auth_user
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    access_key TEXT        NOT NULL,
    chat_id    VARCHAR(20) NOT NULL,
    UNIQUE (chat_id)
);
CREATE TABLE IF NOT EXISTS calendar
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(200) NOT NULL,
    auth_user_id INT          NOT NULL,
    FOREIGN KEY (auth_user_id)
        REFERENCES auth_user (id) ON DELETE CASCADE
);